services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 443:443
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: realm
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_HTTP_TLS_CERTIFICATE: /auth/certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /auth/certs/domain.key
    volumes:
      - ./registry:/var/lib/registry
      - ./auth:/auth
