server:
  disable: true

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://HOST_URL/loki/api/v1/push

scrape_configs:
  - job_name: runner
  
    static_configs:
      - labels:
          machine: mirego-shr-01
          __path__: /logfiles/*.log

    pipeline_stages:
      - regex:
          expression: "^(?P<timestamp>\\d+/\\d+/\\d+ \\d+:\\d+:\\d+) (?P<content>.*)$"
      - timestamp:
          source: timestamp
          format: 2006/01/02 15:04:05
          location: "America/Toronto"
      - output:
          source: content
