version: '2'

services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - ./grafana/:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: http://HOST_URL:3000
  
  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki:/etc/loki

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - ./promtail:/promtail
      - /Users/admin/vm:/logfiles
    command: -config.file=/promtail/config.yaml
